- name: install_app
  hosts: all
  become: yes

  vars:
    pakages:
     - htop
     - mc
     - vim
  tasks:
    - name: install app
      apt:
        pkg: "{{pakages}}"
        state: latest
      