- name: install_app
  hosts: all
  become: yes

  vars:
    pakages:
     - htop
     - mc
     - vim
    file_src: /home/stayasinic/hdd1_temp/git/dotfiles/file123
    file_dest: /root
  
  tasks:
    - name: install app
      apt:
        pkg: "{{pakages}}"
        state: latest
      
    - name: copy file
      copy:
        src: "{{file_src}}"
        dest: "{{file_dest}}"
        mode: 0777